name: Semgrep Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Semgrep
      - name: Install Semgrep
        run: pip install semgrep

      # Run Semgrep (Dashboard mode)
      - name: Run Semgrep Scan
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        run: semgrep ci --verbose